### ISSUE TITLE
server copy not updating

### ISSUE THREAD

**Issue by lonelyjoeparker** [sotones/sotones#1]
deployment server not updating with master branch copy.

**Comment by bobwade** [comment]
lovevintagebcn@a2plcpnl0078 [~/public_html/republicofwessex.com/wp-content/theme
s/sotones]$ git push
To ssh://git@github.com/sotones/sotones.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'ssh://git@github.com/sotones/sotones.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes before pushing again.  See the 'Note about
fast-forwards' section of 'git push --help' for details.

**Comment by bobwade** [comment]
I've added a ssh key to my github account from the server, and changed the remote url in the git config file on the server as described in the answer here: 

http://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

**Comment by bobwade** [comment]
Okay, I think I've finally got it sorted, just managed to push, logged out of the ssh and tried to connect again and it worked, so looking good :)

**Comment by lonelyjoeparker** [comment]
:D

On 29 November 2015 at 19:40, bob wade <notifications@github.com> wrote:

> Closed #1 <https://github.com/sotones/sotones/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sotones/sotones/issues/1#event-477159093>.
>



-- 
Joe Parker
t: +44 (0) 20 7703 8988
w: +44 (0) 20 8332 5063
e: joe@lonelyjoeparker.com
b: lonelyjoeparker.com
tweets: lonelyjoeparker <http://www.twitter.com/lonelyjoeparker>

Facebook | Myspace | Skype | Twitter :: /lonelyjoeparker
LinkedIn: http://www.linkedin.com/pub/b/292/3a4
Soundcloud: http://www.soundcloud.com/lonely-joe-parker
¡Carnivale De Sotones! - Sotones.co.uk <http://sotones.co.uk/> - For all
release, listings and artist info...

This is a private email and does not necessarily represent the views of the
sender or any third parties. If you have received this email in error,
please return to the sender and delete the original, thanks!
